# The URL the site will be built for
base_url = "https://quinnromanek.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The theme we are using
theme = "sam"

title = "Quinn Romanek"

[extra]
# Put all your custom variables here
sam_menu = [
  { text = "flash games", link = "/flash-games" },
  { text = "github", link = "https://github.com/quinnromanek" },
  { text = "linkedin", link = "https://www.linkedin.com/in/quinn-romanek-1a347478" }
]
